In [48]:
import pandas as pd
import numpy as np

In [49]:
resume_df = pd.read_csv('/content/resumes_dataset.csv')
resume_df

,candidate_id,name,email,phone,education,experience_years,skills,projects,expected_role
0,1,Rahul Sharma,rahul.sharma@example.com,9876543210,B.Tech CSE,2,"Python, SQL, Machine Learning, Pandas, Scikit-...",Credit Card Fraud Detection,ML Engineer
1,2,Priya Singh,priya.singh@example.com,9123456780,MCA,1,"Java, Spring Boot, MySQL, Git",Inventory Management System,Java Developer
2,3,Aman Verma,aman.verma@example.com,9988776655,B.Tech IT,3,"React, HTML, CSS, JavaScript, Git",E-commerce Website,Frontend Developer
3,4,Neha Gupta,neha.gupta@example.com,9811122233,B.Tech CSE,1,"Python, Pandas, Excel, SQL, Power BI",Sales Dashboard,Data Analyst
4,5,Rohit Mishra,rohit.mishra@example.com,9765432109,B.Tech CSE,4,"Python, TensorFlow, Deep Learning, Docker, Git",Image Classification,AI Engineer
5,6,Sneha Yadav,sneha.yadav@example.com,9345678912,B.Tech IT,2,"Node.js, Express, MongoDB, REST API",Task Manager API,Backend Developer
6,7,Vikas Kumar,vikas.kumar@example.com,9456781234,B.Tech CSE,2,"Python, SQL, Statistics, Machine Learning",Customer Churn Prediction,Data Scientist
7,8,Pooja Patel,pooja.patel@example.com,9567812345,BCA,1,"Flutter, Firebase, Dart",Expense Tracker,Mobile Developer
8,9,Arjun Rao,arjun.rao@example.com,9789012345,B.Tech CSE,5,"AWS, Docker, Kubernetes, Linux, Git",CI/CD Pipeline,DevOps Engineer
9,10,Karan Singh,karan.singh@example.com,9898989898,B.Tech CSE,2,"Python, NLP, Scikit-learn, SQL, Git",Resume Screening AI,ML Engineer

In [50]:
job_df = pd.read_csv('/content/job_descriptions_dataset.csv')
job_df

,job_id,job_title,required_skills,min_experience,education
0,1,ML Engineer,"Python, Machine Learning, SQL, Scikit-learn, Git",1,B.Tech
1,2,Data Scientist,"Python, Pandas, Statistics, SQL, Machine Learning",2,B.Tech
2,3,Data Analyst,"Excel, SQL, Power BI, Python",1,Graduate
3,4,Java Developer,"Java, Spring Boot, MySQL, Git",1,B.Tech
4,5,Frontend Developer,"React, HTML, CSS, JavaScript, Git",1,Graduate
5,6,Backend Developer,"Node.js, Express, MongoDB, REST API",2,Graduate
6,7,DevOps Engineer,"AWS, Docker, Kubernetes, Linux, Git",3,B.Tech
7,8,AI Engineer,"Python, TensorFlow, Deep Learning, Docker",2,B.Tech
8,9,Mobile Developer,"Flutter, Dart, Firebase",1,Graduate
9,10,Python Developer,"Python, Flask, SQL, Git",1,Graduate

In [51]:
def extract_resume_skill_set(resume_df):
  resumes = resume_df["skills"]
  resume_skills_set = []

  for skill in resumes:
    skill = skill.split(',')
    cleaned_skill = []
    for s in skill:
      s = s.lower().strip()
      cleaned_skill.append(s)
    resume_set = set(cleaned_skill)
    resume_skills_set.append(resume_set)
  return resume_skills_set

resume_skills_set = extract_resume_skill_set(resume_df)
resume_skills_set

[{'machine learning', 'pandas', 'python', 'scikit-learn', 'sql'},
 {'git', 'java', 'mysql', 'spring boot'},
 {'css', 'git', 'html', 'javascript', 'react'},
 {'excel', 'pandas', 'power bi', 'python', 'sql'},
 {'deep learning', 'docker', 'git', 'python', 'tensorflow'},
 {'express', 'mongodb', 'node.js', 'rest api'},
 {'machine learning', 'python', 'sql', 'statistics'},
 {'dart', 'firebase', 'flutter'},
 {'aws', 'docker', 'git', 'kubernetes', 'linux'},
 {'git', 'nlp', 'python', 'scikit-learn', 'sql'}]

In [90]:
def extract_job_skill_set(job_df):
  prefered_job_id = int(input("Enter your preferd Job ID : "))

  required_skills = job_df.loc[prefered_job_id==job_df["job_id"],"required_skills"].tolist()
  for skill in required_skills:
    skill = skill.split(",")
    cleaned_skill = []
    for s in skill:
      s = s.lower().strip()
      cleaned_skill.append(s)
    required_skills_set = set(cleaned_skill)
  return required_skills_set


required_skills_set = extract_job_skill_set(job_df)
required_skills_set

Enter your preferd Job ID : 10

{'flask', 'git', 'python', 'sql'}

In [75]:
def match_skills(resume_skills_set,required_skills_set):
  match_skills = []
  for matched_skill in resume_skills_set:
    matched_skill = matched_skill & required_skills_set
    match_skills.append(matched_skill)
  return match_skills
#resume_skills_set = extract_resume_skill_set(resume_df)

#required_skills_set = extract_job_skill_set(job_df)
match_skill = match_skills(resume_skills_set,required_skills_set)
match_skill

[{'python'},
 set(),
 set(),
 {'python'},
 {'deep learning', 'docker', 'python', 'tensorflow'},
 set(),
 {'python'},
 set(),
 {'docker'},
 {'python'}]

In [76]:
def missing_skills(resume_skills_set,required_skills_set):
  missing_skills = []
  for resume_set in resume_skills_set:
    missed_skills  = required_skills_set - resume_set
    missing_skills.append(missed_skills)
  return missing_skills

missing_skill = missing_skills(resume_skills_set,required_skills_set)
missing_skill

[{'deep learning', 'docker', 'tensorflow'},
 {'deep learning', 'docker', 'python', 'tensorflow'},
 {'deep learning', 'docker', 'python', 'tensorflow'},
 {'deep learning', 'docker', 'tensorflow'},
 set(),
 {'deep learning', 'docker', 'python', 'tensorflow'},
 {'deep learning', 'docker', 'tensorflow'},
 {'deep learning', 'docker', 'python', 'tensorflow'},
 {'deep learning', 'python', 'tensorflow'},
 {'deep learning', 'docker', 'tensorflow'}]

In [65]:
def skill_match_percentage(match_skills, required_skills_set):

    percentage = []

    for matched in match_skills:

        percent = (len(matched)/len(required_skills_set))*100

        percentage.append(percent)

    return percentage
resume_skills_set = extract_resume_skill_set(resume_df)

required_skills_set = extract_job_skill_set(job_df)


percentage = skill_match_percentage(match_skills(resume_skills_set, required_skills_set), required_skills_set)

print(percentage)

Enter your preferd Job ID : 8
[25.0, 0.0, 0.0, 25.0, 100.0, 0.0, 25.0, 0.0, 25.0, 25.0]

In [77]:
def prepare_result(resume_df,
                   matched_skills,
                   missing_skills,
                   percentage):

    result_df = pd.DataFrame({
    "Name": resume_df["name"],
    "Matched Skills": matched_skills,
    "Missing Skills": missing_skills,
    "Match %": percentage
    })
    result_df = result_df.sort_values(by="Match %",ascending=False).reset_index(drop=True)

    return result_df
result_display = prepare_result(resume_df, match_skills(resume_skills_set, required_skills_set), missing_skills(resume_skills_set, required_skills_set), percentage)
result_display

,Name,Matched Skills,Missing Skills,Match %
0,Rohit Mishra,"{python, deep learning, tensorflow, docker}",{},100.0
1,Rahul Sharma,{python},"{deep learning, tensorflow, docker}",25.0
2,Karan Singh,{python},"{deep learning, tensorflow, docker}",25.0
3,Neha Gupta,{python},"{deep learning, tensorflow, docker}",25.0
4,Arjun Rao,{docker},"{python, deep learning, tensorflow}",25.0
5,Vikas Kumar,{python},"{deep learning, tensorflow, docker}",25.0
6,Priya Singh,{},"{python, deep learning, tensorflow, docker}",0.0
7,Aman Verma,{},"{python, deep learning, tensorflow, docker}",0.0
8,Sneha Yadav,{},"{python, deep learning, tensorflow, docker}",0.0
9,Pooja Patel,{},"{python, deep learning, tensorflow, docker}",0.0

In [94]:
def main():

    # Step 1
    resume_skills_set = extract_resume_skill_set(resume_df)

    # Step 2
    required_skills_set = extract_job_skill_set(job_df)

    # Step 3
    match_skill = match_skills(
        resume_skills_set,
        required_skills_set
    )

    # Step 4
    missing_skill = missing_skills(
        resume_skills_set,
        required_skills_set
    )

    # Step 5
    percentage = skill_match_percentage(
        match_skill,
        required_skills_set
    )

    # Step 6
    result_display = prepare_result(
        resume_df,
        match_skill,
        missing_skill,
        percentage
    )

    return result_display
main()

Enter your preferd Job ID : 8

,Name,Matched Skills,Missing Skills,Match %
0,Rohit Mishra,"{python, deep learning, tensorflow, docker}",{},100.0
1,Rahul Sharma,{python},"{deep learning, tensorflow, docker}",25.0
2,Karan Singh,{python},"{deep learning, tensorflow, docker}",25.0
3,Neha Gupta,{python},"{deep learning, tensorflow, docker}",25.0
4,Arjun Rao,{docker},"{python, deep learning, tensorflow}",25.0
5,Vikas Kumar,{python},"{deep learning, tensorflow, docker}",25.0
6,Priya Singh,{},"{python, deep learning, tensorflow, docker}",0.0
7,Aman Verma,{},"{python, deep learning, tensorflow, docker}",0.0
8,Sneha Yadav,{},"{python, deep learning, tensorflow, docker}",0.0
9,Pooja Patel,{},"{python, deep learning, tensorflow, docker}",0.0