In [6]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [7]:
resume_df = pd.read_csv("/content/resumes_dataset.csv")
resume_df

,candidate_id,name,email,phone,education,experience_years,skills,projects,expected_role
0,1,Rahul Sharma,rahul.sharma@example.com,9876543210,B.Tech CSE,2,"Python, SQL, Machine Learning, Pandas, Scikit-...",Credit Card Fraud Detection,ML Engineer
1,2,Priya Singh,priya.singh@example.com,9123456780,MCA,1,"Java, Spring Boot, MySQL, Git",Inventory Management System,Java Developer
2,3,Aman Verma,aman.verma@example.com,9988776655,B.Tech IT,3,"React, HTML, CSS, JavaScript, Git",E-commerce Website,Frontend Developer
3,4,Neha Gupta,neha.gupta@example.com,9811122233,B.Tech CSE,1,"Python, Pandas, Excel, SQL, Power BI",Sales Dashboard,Data Analyst
4,5,Rohit Mishra,rohit.mishra@example.com,9765432109,B.Tech CSE,4,"Python, TensorFlow, Deep Learning, Docker, Git",Image Classification,AI Engineer
5,6,Sneha Yadav,sneha.yadav@example.com,9345678912,B.Tech IT,2,"Node.js, Express, MongoDB, REST API",Task Manager API,Backend Developer
6,7,Vikas Kumar,vikas.kumar@example.com,9456781234,B.Tech CSE,2,"Python, SQL, Statistics, Machine Learning",Customer Churn Prediction,Data Scientist
7,8,Pooja Patel,pooja.patel@example.com,9567812345,BCA,1,"Flutter, Firebase, Dart",Expense Tracker,Mobile Developer
8,9,Arjun Rao,arjun.rao@example.com,9789012345,B.Tech CSE,5,"AWS, Docker, Kubernetes, Linux, Git",CI/CD Pipeline,DevOps Engineer
9,10,Karan Singh,karan.singh@example.com,9898989898,B.Tech CSE,2,"Python, NLP, Scikit-learn, SQL, Git",Resume Screening AI,ML Engineer

In [8]:
job_description_df = pd.read_csv("/content/job_descriptions_dataset.csv")
job_description_df

,job_id,job_title,required_skills,min_experience,education
0,1,ML Engineer,"Python, Machine Learning, SQL, Scikit-learn, Git",1,B.Tech
1,2,Data Scientist,"Python, Pandas, Statistics, SQL, Machine Learning",2,B.Tech
2,3,Data Analyst,"Excel, SQL, Power BI, Python",1,Graduate
3,4,Java Developer,"Java, Spring Boot, MySQL, Git",1,B.Tech
4,5,Frontend Developer,"React, HTML, CSS, JavaScript, Git",1,Graduate
5,6,Backend Developer,"Node.js, Express, MongoDB, REST API",2,Graduate
6,7,DevOps Engineer,"AWS, Docker, Kubernetes, Linux, Git",3,B.Tech
7,8,AI Engineer,"Python, TensorFlow, Deep Learning, Docker",2,B.Tech
8,9,Mobile Developer,"Flutter, Dart, Firebase",1,Graduate
9,10,Python Developer,"Python, Flask, SQL, Git",1,Graduate

In [9]:
job_description_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_id           10 non-null     int64
 1   job_title        10 non-null     object
 2   required_skills  10 non-null     object
 3   min_experience   10 non-null     int64
 4   education        10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [10]:
def extract_skills_from_resume(resume_df):
  skills = []
  for skill in resume_df["skills"]:
     skills.append(skill)

  return skills
candidate_skills = extract_skills_from_resume(resume_df)
candidate_skills

['Python, SQL, Machine Learning, Pandas, Scikit-learn',
 'Java, Spring Boot, MySQL, Git',
 'React, HTML, CSS, JavaScript, Git',
 'Python, Pandas, Excel, SQL, Power BI',
 'Python, TensorFlow, Deep Learning, Docker, Git',
 'Node.js, Express, MongoDB, REST API',
 'Python, SQL, Statistics, Machine Learning',
 'Flutter, Firebase, Dart',
 'AWS, Docker, Kubernetes, Linux, Git',
 'Python, NLP, Scikit-learn, SQL, Git']

In [11]:
def extract_skills_from_job_description(job_description_df):
   prefered_job_id = int(input("Enter your Job Id which you want in requried skills : "))

   required_skills = job_description_df.loc[job_description_df["job_id"]==prefered_job_id,"required_skills"].tolist()
   return required_skills
required_skills = extract_skills_from_job_description(job_description_df)

required_skills

Enter your Job Id which you want in requried skills : 8

['Python, TensorFlow, Deep Learning, Docker']

In [34]:
def calculate_similarity(candidate_skills,required_skills):
  vector = TfidfVectorizer()
  corpus = candidate_skills+required_skills
  matrix = vector.fit_transform(corpus)
  simi = cosine_similarity(matrix)
  simi_df = pd.DataFrame(simi)
  score = (simi_df.iloc[-1,:-1])
  percentage =(score*100).tolist()
  percentage_df = pd.DataFrame({"Name":resume_df["name"],"percentage": percentage})
  return percentage_df
calculated_similarity = calculate_similarity(candidate_skills,required_skills)
calculated_similarity

           Name  percentage
0  Rahul Sharma   22.284101
1   Priya Singh    0.000000
2    Aman Verma    0.000000
3    Neha Gupta    8.603169
4  Rohit Mishra   93.979112
5   Sneha Yadav    0.000000
6   Vikas Kumar   26.421412
7   Pooja Patel    0.000000
8     Arjun Rao   17.084877
9   Karan Singh    9.624536

In [42]:
def rank_resume(percentage_df):
  ranked_df = percentage_df.sort_values(by="percentage",ascending = False)
  return ranked_df.reset_index(drop = True)
ranked_df = rank_resume(calculated_similarity)
ranked_df

           Name  percentage
0  Rohit Mishra   93.979112
1   Vikas Kumar   26.421412
2  Rahul Sharma   22.284101
3     Arjun Rao   17.084877
4   Karan Singh    9.624536
5    Neha Gupta    8.603169
6   Priya Singh    0.000000
7    Aman Verma    0.000000
8   Sneha Yadav    0.000000
9   Pooja Patel    0.000000

In [57]:
def display_result(ranked_df):
  print("="*30)
  print("RANKED RESUME")
  print("="*30)
  print(ranked_df.to_string(index=False))
display_result(ranked_df)

==============================
RANKED RESUME
==============================
        Name  percentage
Rohit Mishra   93.979112
 Vikas Kumar   26.421412
Rahul Sharma   22.284101
   Arjun Rao   17.084877
 Karan Singh    9.624536
  Neha Gupta    8.603169
 Priya Singh    0.000000
  Aman Verma    0.000000
 Sneha Yadav    0.000000
 Pooja Patel    0.000000

In [60]:
def main():

    # Step 1
    candidate_skills = extract_skills_from_resume(resume_df)

    # Step 2
    required_skills = extract_skills_from_job_description(job_description_df)

    # Step 3
    calculated_similarity = calculate_similarity(
        candidate_skills,
        required_skills
    )

    # Step 4
    ranked_df = rank_resume(calculated_similarity)

    # Step 5
    display_result(ranked_df)
main()

Enter your Job Id which you want in requried skills : 4
==============================
RANKED RESUME
==============================
        Name  percentage
 Priya Singh  100.000000
 Karan Singh    8.936401
Rohit Mishra    8.493923
   Arjun Rao    8.422990
  Aman Verma    8.155135
Rahul Sharma    0.000000
 Sneha Yadav    0.000000
  Neha Gupta    0.000000
 Pooja Patel    0.000000
 Vikas Kumar    0.000000